[package]
name = "rust_openai"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-openai = "0.15.0"
tokio = { version = "1.29.1", features = ["full"] }
dotenv = "0.15.0"